### ISSUE TITLE
Future of this repo: WASM

### ISSUE THREAD

**Issue by maxence-charriere** [maxence-charriere/app#262]
Hello, it's been a while I did not pushed any update on this repository. I want to give a heads up on what is going on.

## What happened?

During the past months I experimented a lot with Windows and a little bit with Linux. I was pretty close to ship a release for [Windows](https://github.com/murlokswarm/app/issues/141) but the reason why it did not happened  was because it did not met the quality I expected: the Window driver was too hacky and too unstable.

Beside, I experimented a little bit with Linux, it was promising but between all these cross platform developments, I realised it was too big for me alone to handle all the different abstractions.

## What's next?

I had been working on this repo for 3 years and honestly, I don't want to give up. I like the way it works to build apps and I believe it have the potential to be useful to a lot of people.

A couple of month ago, Go 1.11 was shipped with experimental support for web assembly. I gave it a try and ported the package to work with the wasm achitecture.

I'am pretty convinced with the result and here are some points I want to highlight:
- Web is the only platform that works everywhere with specified standards.
- Wasm lives in the Go repository and gonna be maintained and optimized by top engineers.
- This package will be focused on 1 platform and I want the best for what I use. So no inequalities between MacOS and Windows.
- Full DOM access with [syscall/js](https://golang.org/pkg/syscall/js/).
- Desktop app development will still be possible by using this package with [Electron](https://electronjs.org).
- I also built another [go package](https://github.com/maxence-charriere/murlok) based on my MacOS work that allows to run a website as an app and could be used with this repo.

## Where are we now?

The WASM refactor is already implementend on the wasm branch. It will be improved until the Go 1.12 release and be merged on master a short time after. It provide the same api to build an UI and an `http.Handler` to serve the app that can be used with any `http.Server`.

You can already see the result of that work there: [app demo](https://app-demo-232021.appspot.com)

Here are the known issues:
- Can trigger an Out of memory error on mobile (waiting a fix from Go 1.12).
- Does not work with Microsot Edge (Trying to fix it but in the worst case, Edge will based on webkit soon).
- Still have to write documentation about how to use it.
- Go wasm is still experimental and syscall/js can be modified.

## A last word
Changing the direction of this package has been a pretty hard decision to take. I get it if it sounds less interesting.

I just want to say that I see an oportunity with an emerging technology (wasm) and I really believe it could make a difference.

Feedbacks are more than welcome.
Thank you so much for following this work until now.

**Comment by illyohs** [comment]
Shame Linux is being dropped will have to find will have to find an alternative. :disappointed:
