### ISSUE TITLE
Cannot close port after closing the app

### ISSUE THREAD

**Issue by talentlessguy** [maxence-charriere/app#283]
I started the app, then closed terminal but the app is still running. How can I kill the app totally? Even pc reload didn't help

also, please make ports autoclosing, not to have this problem every time.

![image](https://user-images.githubusercontent.com/35937217/59966328-b683dd80-9523-11e9-8a83-fb4b980a467b.png)

**Comment by maxence-charriere** [comment]
This package have support for offline mode with the browser service workers. Even when you stop the server, the browser will load the page because it is cached.

**Comment by maxence-charriere** [comment]
```make ports autoclosing```

This package is mainly providing a `http.handler`
```go
func main() {
	// Setup the http handler to serve the web assembly app.
	http.Handle("/", &app.Handler{
		LoadingLabel: "loading",
		Name:         "app demo",
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "3000"
		log.Printf("Defaulting to port %s", port)
	}

	// Launches the server :S.
	if err := http.ListenAndServe(fmt.Sprintf(":%s", port), nil); err != nil {
		log.Fatal(err)
	}
}
```

You are free to handle the server resources the way you want.

**Comment by talentlessguy** [comment]
Okay, thanks for detailed explanation! Now I need to find out how to disable a worker...
