### ISSUE TITLE
linkerror:webassembly.instantiate():import #20 module="go" function="syscall/js.copybytestogo"error:function import requires a callable"

### ISSUE THREAD

**Issue by BenDerPan** [maxence-charriere/app#288]
#### I tested with below steps:
1. `goapp init -v`
2. `goapp build -v`
3. `goapp run -v -b default`  

#### then the web page dispaly the error:
```Shell:
linkerror:webassembly.instantiate():import #20 module="go" function="syscall/js.copybytestogo"error:function import requires a callable"
```

**Comment by maxence-charriere** [comment]
Hello thanks for reporting this.
I ll take a look on this by the end of the day.

In the meantime, can you try to launch the following commands and retry:

goapp update -v

**Comment by maxence-charriere** [comment]
just pushed a fix => https://github.com/maxence-charriere/app/pull/289

run 
```sh
goapp update -v
```

Let me know how it goes.

**Comment by BenDerPan** [comment]
yes, It's work now, thanks :)

**Comment by maxence-charriere** [comment]
Awesome :)
