### ISSUE TITLE
How to save some configuration 

### ISSUE THREAD

**Issue by yhcd** [maxence-charriere/app#294]
for example, save the current city or username
through server or wasm

**Comment by maxence-charriere** [comment]
Hello,
You can use the `LocalStorage` or `SessionStorage`.
https://godoc.org/github.com/maxence-charriere/app/pkg/app#pkg-variables

Those maps to the browser localStorage and sessionStorage but data put inside with this package are encrypted.

Example:
```go
// Set
if err := app.LocalStorage.Set("myKey", "hello"); err != nil {
    // handle error ...
    return
}

// Get
var s string
if err := app.LocalStorage("myKey", &s); err != nil {
    // handle error ...
}
fmt.Println(s)
```
