### ISSUE TITLE
In goapp.js activate should remove old cache. 

### ISSUE THREAD

**Issue by bgokden** [maxence-charriere/app#302]
When a service worker updated due to a new version released. New versions of the files should be cached and old ones should be removed.

Google has a recommended way of doing this explained here:
https://developers.google.com/web/fundamentals/primers/service-workers#update-a-service-worker

We can change activate the function to this if you accept I would like to create a pull request.

```javascript
self.addEventListener('activate', function(event) {
  
  console.log('goapp worker', etag, 'is activated')

  var cacheWhitelist = [
        {{range .Paths}}'{{.}}',
        {{end}}'/'
      ];

  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.map(function(cacheName) {
          if (cacheWhitelist.indexOf(cacheName) === -1) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});
```

**Comment by maxence-charriere** [comment]
Also this is an open source project, if you think you have a fix or an improvement, feel free to open a PR.
I ll review it :).
