### ISSUE TITLE
Issue while building demo app

### ISSUE THREAD

**Issue by sujithkvarghese1982** [maxence-charriere/app#305]
Hi,
     I am getting an error as follows while executing the command "goapp run -v -b chrome"
‣ generating service worker
x generating /home/go/src/github.com/maxence-charriere/app/demo/cmd/demo-server/web/goapp.js failed: template: /home/go/src/github.com/maxence-charriere/app/demo/cmd/demo-server/web/goapp.js:6: function "Paths" not defined

What might be the issue? Need help.

**Comment by maxence-charriere** [comment]
Sorry about that, stupid typo error that I did not detect during last push.

Just fixed it.
You can run `goapp update -v` and you will be able to build it.

Thank you so much for spotting this!

**Comment by sujithkvarghese1982** [comment]
Thanks for very quick response.
