### ISSUE TITLE
Handling timers for baneer update

### ISSUE THREAD

**Issue by sujithkvarghese1982** [maxence-charriere/app#307]
Hi,
     I was trying out to add timer based custom banners, how should i proceed to implement display and closing of banner based on timer expiry? When i try to render the banner based on timer expiry the page gets delayed based on the time i give. Need insight on how to add the custom callback to implement the events and rendering multiple banners.

**Comment by maxence-charriere** [comment]
I would need you share a the code you use to help you with this.

**Comment by sujithkvarghese1982** [comment]
Thanks for the support, below is my code as defined as Banner.go,
`// +build wasm

package main

import (
	"syscall/js"
	"time"

	"github.com/maxence-charriere/app/pkg/app"
)

type timerstat interface {
	gocustumTimer()
}

// Banner is a component that describes a banner popup.
type Banner struct {
	message     string
	timerperiod int
}

func (b *Banner) gocustumTimer() {

	time.Sleep(time.Duration(b.timerperiod) * 1000 * time.Millisecond)
	app.Render(b)
}

func timerinit(list []timerstat) {

	for _, val := range list {
		go val.gocustumTimer()
	}
}

// OnMount initializes the component when it is mounted.
func (h *Banner) OnMount() {

	//var err error
	app.Render(h)

	b1 := Banner{"Banner 1", 1}
	//b2 := Banner{"Banner 2", 2}

	timerinit([]timerstat{&b1})

}

// Render returns what to display.
//
// The onchange="Name" binds the onchange value to the Hello.Name
// field.
func (h *Banner) Render() string {
	return `
<div class="w3-content" style="background-color:black;width:100%;height:100%">
	<main>
		<h1>
		{{if .message}}
			<img class="mySlides" src="https://static.vecteezy.com/system/resources/previews/000/095/529/original/best-offer-sale-banner-vector.jpg" alt="custom_html_banner" style="width:30%">
			<p>"Banner closing in"</p>
		{{else}}
			<p>"Display failed"</p>
		{{end}}
		</h1>
 	<main>
</div>
	`
}`

Here the image mentioned in the div tag and some text i need to show as part of a banner, and when the timer stops needs to close it or render only the white background. How do i proceed?

**Comment by maxence-charriere** [comment]
could you copy/paste your snippet in the conversation or share a GitHub repo?

**Comment by sujithkvarghese1982** [comment]
ok below is the code,

// +build wasm

package main

import (
	"github.com/maxence-charriere/app/pkg/app"
)

type timerstat interface {
	gocustumTimer()
}

// Banner is a component that describes a banner popup.
type Banner struct {
	Message string
	Timerperiod int
}

func (b *Banner) gocustumTimer() {

	//time.Sleep(time.Duration(b.Timerperiod) * 1000 * time.Millisecond)
	app.Render(b)
}

func timerinit(list []timerstat) {

	for _, val := range list {
		go val.gocustumTimer()
	}
}

// OnMount initializes the component when it is mounted.
func (h *Banner) OnMount() {

	//var err error
	h.Message = "Banner 1"
	//h.Timerperiod = 1
	app.Render(h)

	b1 := Banner{"Banner 1", 1}
	b2 := Banner{"Banner 2", 2}

	timerinit([]timerstat{&b1})

}

// Render returns what to display.
//
// The onchange="Name" binds the onchange value to the Hello.Name
// field.
func (h *Banner) Render() string {
	return `
<div class="w3-content" style="background-color:black;width:100%;height:100%">
	<main>
		<h1>
		{{if .Message}}
			<img class="mySlides" src=best-offer-sale-banner-vector.jpg" alt="custom_html_banner" style="width:30%">
			<p>"Banner closing in"</p>
		{{else}}
			<p>"Display failed"</p>
		{{end}}
		</h1>
 	<main>
</div>
	`
}

**Comment by maxence-charriere** [comment]
Look like you are not updating the ui to stop display the time =>
```go
func (b *Banner) gocustumTimer() {

	//time.Sleep(time.Duration(b.Timerperiod) * 1000 * time.Millisecond)

        // ==> b.Message = "" ?
	app.Render(b)
}
```

another problem Is that this is launched on a groutine. You should update the ui on the `ui goroutine`

``` go
func (b *Banner) gocustumTimer() {
        app.UI(func(){
            b.Message = ""
            app.Render(b)
        })
}
```

Still, implemented as it is, after your timer, you should see the `Display failed` message.

**Comment by maxence-charriere** [comment]
If I had take on your problem, I ll do something like:
```go
package main

import (
	"time"

	"github.com/maxence-charriere/app/pkg/app"
)

// Banner is a component that describes a banner popup.
type Banner struct {
	Visible   bool
	Remaining time.Duration
	ticker    *time.Ticker
}

// OnMount initializes the component when it is mounted.
func (b *Banner) OnMount() {
	b.Visible = true
	app.Render(b)

	b.ticker = time.NewTicker(time.Second)
	go b.startUpdate()
}

func (b *Banner) startUpdate() {
	for range b.ticker.C {
		app.UI(func() {
			remaining := b.Remaining - time.Second
			if remaining <= 0 {
				b.Visible = false
				b.ticker.Stop()
			}

			b.Remaining = remaining
			app.Render(b)
		})
	}
}

// We want to ensure that there is no remaining goroutine if the component
// is dismounted while counting remaining time.
func (b *Banner) OnDismount() {
	b.ticker.Stop()
}

// Render returns what to display.
//
// The onchange="Name" binds the onchange value to the Hello.Name
// field.
func (b *Banner) Render() string {
	return `
<div class="w3-content" style="background-color:black;width:100%;height:100%">
	<main>
		<h1>
		{{if .Visible}}
			<img class="mySlides" src=best-offer-sale-banner-vector.jpg" alt="custom_html_banner" style="width:30%">
			<p>"Banner closing in {{.Remaining Seconds}}"</p>
		{{end}}
		</h1>
 	<main>
</div>
	`
}

```

**Comment by maxence-charriere** [comment]
Another way to do it would be to use `app.Bind`:

```go
package main

import (
	"time"

	"github.com/maxence-charriere/app/pkg/app"
)

// Banner is a component that describes a banner popup.
type Banner struct {
	Visible   bool
	Remaining time.Duration
}

// OnMount initializes the component when it is mounted.
func (b *Banner) OnMount() {
	// Create a binding that wait a sec.
	app.Bind("banner.update", b).
		Wait(time.Second).
		Do(b.update)

	b.Visible = true
	b.Remaining = time.Second * 5
	app.Render(b)

	// We trigger the binding that will be executed a sec later.
	app.Emit("banner.update")
}

func (b *Banner) update() {
	remaining := b.Remaining - time.Second

	// Update visibility.
	if remaining <= 0 {
		b.Visible = false
		app.Render(b)
		return
	}

	// Update counter.
	b.Remaining = remaining
	app.Render(b)

	// We re trigger the binding to be executed a sec later.
	app.Emit("banner.update")
}

// Render returns what to display.
//
// The onchange="Name" binds the onchange value to the Hello.Name
// field.
func (b *Banner) Render() string {
	return `
<div class="w3-content" style="background-color:black;width:100%;height:100%">
	<main>
		<h1>
		{{if .Visible}}
			<img class="mySlides" src=best-offer-sale-banner-vector.jpg" alt="custom_html_banner" style="width:30%">
			<p>"Banner closing in {{.Remaining Seconds}}"</p>
		{{end}}
		</h1>
 	<main>
</div>
	`
}
```

**Comment by sujithkvarghese1982** [comment]
Hi,
     Thanks for the update, really appreciate the support. I can see cleary i went wrong on the UI go routine which i should have used instead of the normal one. I even added the ticker functionality at one point but found out that the UI rendering is delayed due to it. Cancel operation is a good point, thanks for that. 

I have few doubts though while i went through the goapp code. 
1. How does the log work for the goapp applications like examples hello,city etc. I can see the server outputs logs to the standard output. Do i have to output the logs to a file? or is there any other mechanism?
2. The callback functions like OnMount() and OnDisMount(). How they are getting called? It is clear to me how Render() is getting called through the Combo interface since we are passing using Import(), but not the others. I didn't see the Mounter interface getting passed though?
3. Is there a way i can separately run wasm server as one process and example go applications like hello, city etc separately as another process not inside browser even though i don't see the output in the browser. This is just to make sure i get by go routine functions covered.

Thank you.

**Comment by maxence-charriere** [comment]
1. The log is just a package that I put in this repo because it allow to put context in messages via tags. You are the one that take the decision of using it. Standard `fmt` or `log` packages are more than enough to do the same job. I think its gonna be hard to log in a file on the browser side (wasm) but you do whatever you want on the server.
2. `OnMount`, `OnDimount` are just functions to satisfy interfaces. There is a virtual Dom in background and when a component is mounted or dismounted, those method are called if your component satisfies the [Mounter](https://godoc.org/github.com/maxence-charriere/app/pkg/app#Mounter) or [Dismounter](https://godoc.org/github.com/maxence-charriere/app/pkg/app#Dismounter) interfaces.
3. There is no wasm server. `goapp` build 2 programs and package them together:
    - The wasm file that contains the code executed in the browser
    - The server that serve the wasm file and other resources

You Can still unit test wasm file but it causes problem if you start to use `system/js` package.
It in my plans to wrap this package within the repo in order to be able unit test everything seamlessly.

**Comment by sujithkvarghese1982** [comment]
Thanks for the suggestions one again.
