### ISSUE TITLE
open /home/username/go/src/github.com/maxence-charriere/app/logo.png: no such file or directory

### ISSUE THREAD

**Issue by bh90210** [maxence-charriere/app#309]
Hello @maxence-charriere 

I am trying to build the demo (`goapp init -v `) outsite $GOPATH and I am getting the following error
```
goapp run -v -b default
‣ building wasm app
‣ building server
‣ installing go wasm support file
‣ generating etag
‣ generating service worker
‣ generating icons
x open /home/username/go/src/github.com/maxence-charriere/app/logo.png: no such file or directory
```

search for a solution I came across this thread and comment in particular https://github.com/golang/go/issues/31529#issuecomment-484944113

indeed after `go get -u -v github.com/maxence-charriere/app/cmd/goapp` while 
`goapp init -v` & `goapp build -v` & `goapp update -v` work fine the directory `$GOPATH/go/src/github.com/maxence-charriere/app/` doesn't exist.

Am I doing something wrong?

**Comment by maxence-charriere** [comment]
I think it requires that you have `github.com/maxence-charriere/app` installed with go get.
Usually your go repo are located in  GOPATH/src/...

Unless you are using `go mod`.

If it's the case can you give be the step to reproduce?
- Where you repo is located
- the commands you used before   running `goapp run`

**Comment by bh90210** [comment]
hey, I just saw you answered asap, :+1: 

yes I am using `go mod`, I assumed it was alright since in the getting started the $GOPATH step was marked as optional.

this is what I 've tried
```
$ mkdir app
$ cd app
$ goapp init -v
‣ initializing project layout
‣ generating /home/username/testing/app/cmd/app-server/main.go
‣ generating /home/username/testing/app/cmd/app-wasm/main.go
✔ initialization succeeded
$ go mod init app
go: creating new go.mod: module app
$ goapp build -v
‣ building wasm app
    go: finding github.com/maxence-charriere/app latest
    go: finding golang.org/x/net latest
    app/cmd/app-wasm
‣ building server
    app/cmd/app-server
‣ installing go wasm support file
‣ generating etag
‣ generating service worker
‣ generating icons
x open /home/username/go/src/github.com/maxence-charriere/app/logo.png: no such file or directory
```

**Comment by bh90210** [comment]
uh I am so sorry, this was unrelated to you.

I had `GO111MODULE=on`, to solve my problem I just `GO111MODULE=auto go get -u -v github.com/maxence-charriere/app/cmd/goapp`
