### ISSUE TITLE
[BUG]Cannot run demo out of GOPATH

### ISSUE THREAD

**Issue by linkerlin** [maxence-charriere/app#310]
If I put the demo app out of GOPATH, for example ~/gos/, 
goapp run -v -b chrome 
will report a error:
can't load package: package /Users/xxxxxxxx/gos/demo/cmd/demo-wasm: import "/Users/xxxxxxxx/gos/demo/cmd/demo-wasm": cannot import absolute path

**Comment by jonericcook** [comment]
I get the same error

`
joneric.cook@Work-MacBook-Pro demo % goapp run -v -b chrome
‣ building wasm app
    can't load package: package /Users/joneric.cook/Desktop/demo/cmd/demo-wasm: import "/Users/joneric.cook/Desktop/demo/cmd/demo-wasm": cannot import absolute path
x exit status 1
`

**Comment by CJH9004** [comment]
try `go mod init /`

**Comment by maxence-charriere** [comment]
You have to use `go mod init` while it is still in the go path.
Then do `go mod tidy`
And once those 2 things are done you can move it wherever you want.

Closing this since it is not an issue related to this package.
